const restaurant_test = [
    {
        id:"1",
        restaurant_name:"Koebe",
        house_number:"03",
        ward:"Van Phu",
        district:"Ha Dong",
        city:"Ha Noi",
        longitude:"20.95793277721923",
        latitude:"105.76662543880649",
        description:"Nha hang ban bo ngon nhat Ha Dong voi hon 1020 nam kinh nghiem",
        phone_number:"024432423422",
        email:"banbongon@gmail.com",
        website:"banbongon.com.vn",
        facebook_link:"",
        instagram_link:"",
        id_user_add:"1",
        restaurant_state:"",
        time_added:"",
        id_user_owner:"1",
        rate:"5",
        image:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712810114/foodx/r3r5evz7xpdakx99cjoa.jpg"
    },
    {
        id:"2",
        restaurant_name:"Koebe",
        house_number:"03",
        ward:"Van Phu",
        district:"Ha Dong",
        city:"Ha Noi",
        longitude:"20.95793277721923",
        latitude:"105.76662543880649",
        description:"Nha hang ban bo ngon nhat Ha Dong voi hon 1020 nam kinh nghiem",
        phone_number:"024432423422",
        email:"banbongon@gmail.com",
        website:"banbongon.com.vn",
        facebook_link:"",
        instagram_link:"",
        id_user_add:"1",
        restaurant_state:"",
        time_added:"",
        id_user_owner:"1",
        rate:"5",
        image:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712810114/foodx/r3r5evz7xpdakx99cjoa.jpg"
    },
    {
        id:"3",
        restaurant_name:"Koebe",
        house_number:"03",
        ward:"Van Phu",
        district:"Ha Dong",
        city:"Ha Noi",
        longitude:"20.95793277721923",
        latitude:"105.76662543880649",
        description:"Nha hang ban bo ngon nhat Ha Dong voi hon 1020 nam kinh nghiem",
        phone_number:"024432423422",
        email:"banbongon@gmail.com",
        website:"banbongon.com.vn",
        facebook_link:"",
        instagram_link:"",
        id_user_add:"1",
        restaurant_state:"",
        time_added:"",
        id_user_owner:"1",
        rate:"5",
        image:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712810114/foodx/r3r5evz7xpdakx99cjoa.jpg"
    },
    {
        id:"3",
        restaurant_name:"Koebe",
        house_number:"03",
        ward:"Van Phu",
        district:"Ha Dong",
        city:"Ha Noi",
        longitude:"20.95793277721923",
        latitude:"105.76662543880649",
        description:"Nha hang ban bo ngon nhat Ha Dong voi hon 1020 nam kinh nghiem",
        phone_number:"024432423422",
        email:"banbongon@gmail.com",
        website:"banbongon.com.vn",
        facebook_link:"",
        instagram_link:"",
        id_user_add:"1",
        restaurant_state:"",
        time_added:"",
        id_user_owner:"1",
        rate:"5",
        image:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712810114/foodx/r3r5evz7xpdakx99cjoa.jpg"
    },
    {
        id:"3",
        restaurant_name:"Koebe",
        house_number:"03",
        ward:"Van Phu",
        district:"Ha Dong",
        city:"Ha Noi",
        longitude:"20.95793277721923",
        latitude:"105.76662543880649",
        description:"Nha hang ban bo ngon nhat Ha Dong voi hon 1020 nam kinh nghiem",
        phone_number:"024432423422",
        email:"banbongon@gmail.com",
        website:"banbongon.com.vn",
        facebook_link:"",
        instagram_link:"",
        id_user_add:"1",
        restaurant_state:"",
        time_added:"",
        id_user_owner:"1",
        rate:"1",
        image:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712810114/foodx/r3r5evz7xpdakx99cjoa.jpg"
    },
    {
        id:"3",
        restaurant_name:"Koebe",
        house_number:"03",
        ward:"Van Phu",
        district:"Ha Dong",
        city:"Ha Noi",
        longitude:"20.95793277721923",
        latitude:"105.76662543880649",
        description:"Nha hang ban bo ngon nhat Ha Dong voi hon 1020 nam kinh nghiem",
        phone_number:"024432423422",
        email:"banbongon@gmail.com",
        website:"banbongon.com.vn",
        facebook_link:"",
        instagram_link:"",
        id_user_add:"1",
        restaurant_state:"",
        time_added:"",
        id_user_owner:"1",
        rate:"5",
        image:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712810114/foodx/r3r5evz7xpdakx99cjoa.jpg"
    },
]

const user_test = [
    {
        id:"1",
        name:"Asley",
        avatar_link:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712909047/ivvn3honq3owtlvxsib3.png",
        ward:"Doi Can",
        district:"Ba Dinh",
        city:"Ha Noi",
        join_date:"2002-10-3",
        points:"30",
        number_of_reviews:"10",
    },
    {
        id:"2",
        name:"Greyman",
        avatar_link:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712909047/ivvn3honq3owtlvxsib3.png",
        ward:"Doi Can",
        district:"Ba Dinh",
        city:"Ha Noi",
        join_date:"2002-10-3",
        points:"70",
        number_of_reviews:"90",
    },
    {
        id:"3",
        name:"Donald Trump",
        avatar_link:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712909047/ivvn3honq3owtlvxsib3.png",
        ward:"Doi Can",
        district:"Ba Dinh",
        city:"Ha Noi",
        join_date:"2002-10-3",
        points:"3",
        number_of_reviews:"1",
    },
    {
        id:"4",
        name:"Vuong Nguyen",
        avatar_link:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712909047/ivvn3honq3owtlvxsib3.png",
        ward:"Doi Can",
        district:"Ba Dinh",
        city:"Ha Noi",
        join_date:"2002-10-3",
        points:"300",
        number_of_reviews:"100",
    },
    {
        id:"5",
        name:"Nguyen Van B",
        avatar_link:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712909047/ivvn3honq3owtlvxsib3.png",
        ward:"Doi Can",
        district:"Ba Dinh",
        city:"Ha Noi",
        join_date:"2002-10-3",
        points:"302",
        number_of_reviews:"190",
    },
]

const comment_test = [
    {
        id:"1",
        user_name:"Vuong Nguyen",
        restaurant_name:"Koebey",
        user_avatar:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712909047/ivvn3honq3owtlvxsib3.png",
        restaurant_address:"Hoan Kiem, Ha Noi",
        images:["https://res.cloudinary.com/ddinttgy0/image/upload/v1712975007/wyddqeo2js2anlfurrza.jpg","https://res.cloudinary.com/ddinttgy0/image/upload/v1712939452/iyenpa3dqmw6vbsk5gxr.jpg","https://res.cloudinary.com/ddinttgy0/image/upload/v1712939452/jxrjsiowurfmuxmocegi.jpg"],
        review_date:"2024-04-12T12:33:58.000Z",
        review_title:"Supper good restaurant",
        review_content:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores reprehenderit, labore, dolores illo nobis aperiam eum, consectetur itaque sapiente reiciendis et corporis quos mollitia numquam doloribus quod eligendi nulla sequi.",
        star_number:"5",
        like_number:"33",
        dislike_number:"2"
    },
    {
        id:"2",
        user_name:"Lam Nguyen",
        restaurant_name:"Haloi",
        user_avatar:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712909047/ivvn3honq3owtlvxsib3.png",
        restaurant_address:"London, England",
        images:["https://res.cloudinary.com/ddinttgy0/image/upload/v1712975007/wyddqeo2js2anlfurrza.jpg","https://res.cloudinary.com/ddinttgy0/image/upload/v1712939452/iyenpa3dqmw6vbsk5gxr.jpg","https://res.cloudinary.com/ddinttgy0/image/upload/v1712939452/jxrjsiowurfmuxmocegi.jpg"],
        review_date:"2024-04-12T09:54:58.000Z",
        review_title:"Bad restaurant",
        review_content:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores reprehenderit, labore, dolores illo nobis aperiam eum, consectetur itaque sapiente reiciendis et corporis quos mollitia numquam doloribus quod eligendi nulla sequi.",
        star_number:"1",
        like_number:"22",
        dislike_number:"3"
    },
    {
        id:"3",
        user_name:"Van Tran",
        restaurant_name:"Neildaty",
        user_avatar:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712909047/ivvn3honq3owtlvxsib3.png",
        restaurant_address:"New York, America",
        images:["https://res.cloudinary.com/ddinttgy0/image/upload/v1712975007/wyddqeo2js2anlfurrza.jpg","https://res.cloudinary.com/ddinttgy0/image/upload/v1712939452/iyenpa3dqmw6vbsk5gxr.jpg","https://res.cloudinary.com/ddinttgy0/image/upload/v1712939452/jxrjsiowurfmuxmocegi.jpg"],
        review_date:"2024-04-12T01:54:58.000Z",
        review_title:"Expensive restaurant",
        review_content:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores reprehenderit, labore, dolores illo nobis aperiam eum, consectetur itaque sapiente reiciendis et corporis quos mollitia numquam doloribus quod eligendi nulla sequi.",
        star_number:"3",
        like_number:"44",
        dislike_number:"77"
    },
    {
        id:"4",
        user_name:"Asley",
        restaurant_name:"Neildaty",
        user_avatar:"https://res.cloudinary.com/ddinttgy0/image/upload/v1712909047/ivvn3honq3owtlvxsib3.png",
        restaurant_address:"New York, America",
        images:["https://res.cloudinary.com/ddinttgy0/image/upload/v1712975007/wyddqeo2js2anlfurrza.jpg","https://res.cloudinary.com/ddinttgy0/image/upload/v1712939452/iyenpa3dqmw6vbsk5gxr.jpg","https://res.cloudinary.com/ddinttgy0/image/upload/v1712939452/jxrjsiowurfmuxmocegi.jpg"],
        review_date:"2024-04-12T01:54:58.000Z",
        review_title:"Expensive restaurant",
        review_content:"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores reprehenderit, labore, dolores illo nobis aperiam eum, consectetur itaque sapiente reiciendis et corporis quos mollitia numquam doloribus quod eligendi nulla sequi.",
        star_number:"3",
        like_number:"44",
        dislike_number:"77"
    },
]



export {
    restaurant_test,
    user_test,
    comment_test
}